### ISSUE TITLE
`yarn_install` build error: could not find dependency 'sqlite3' of 'websql'

### ISSUE THREAD

**Issue by heronyang** [benjmarks22/blockchain-2pc#7] opened 2022-05-14 23:44 UTC
I tried to build truffle blockchain code with bazel on a blank Ubuntu 22.04 LTS machine and encountered the following error. Does anyone of you happen to know how to resolve?

```
$ bazel run //src/blockchain:compile_blockchain
DEBUG: /home/heronyang/.cache/bazel/_bazel_heronyang/ad9740c75005326aa53e480f56f01ef4/external/build_bazel_rules_nodejs/index.bzl:65:14: node_repository attribute not set and no repository named 'nodejs_toolchains' exists; installing default node
DEBUG: /home/heronyang/.cache/bazel/_bazel_heronyang/ad9740c75005326aa53e480f56f01ef4/external/build_bazel_rules_nodejs/index.bzl:73:14: yarn_install#yarn attribute not set and no repository named 'yarn' exists; installing default yarn
INFO: Repository blockchain_npm instantiated at:
  /home/heronyang/blockchain-2pc/WORKSPACE:44:13: in <toplevel>
  /home/heronyang/.cache/bazel/_bazel_heronyang/ad9740c75005326aa53e480f56f01ef4/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  /home/heronyang/.cache/bazel/_bazel_heronyang/ad9740c75005326aa53e480f56f01ef4/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:975:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'blockchain_npm':
   Traceback (most recent call last):
File "/home/heronyang/.cache/bazel/_bazel_heronyang/ad9740c75005326aa53e480f56f01ef4/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 971, column 24, in _yarn_install_impl
_create_build_files(repository_ctx, "yarn_install", node, repository_ctx.attr.yarn_lock, repository_ctx.attr.generate_local_modules_build_files)
File "/home/heronyang/.cache/bazel/_bazel_heronyang/ad9740c75005326aa53e480f56f01ef4/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 485, column 13, in _create_build_files
fail("generate_build_file.ts failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (result.stdout, result.stderr))
Error in fail: generate_build_file.ts failed: 
STDOUT:

STDERR:
could not find dependency 'sqlite3' of 'websql'
ERROR: /home/heronyang/blockchain-2pc/WORKSPACE:44:13: fetching yarn_install rule //external:blockchain_npm: Traceback (most recent call last):
File "/home/heronyang/.cache/bazel/_bazel_heronyang/ad9740c75005326aa53e480f56f01ef4/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 971, column 24, in _yarn_install_impl
_create_build_files(repository_ctx, "yarn_install", node, repository_ctx.attr.yarn_lock, repository_ctx.attr.generate_local_modules_build_files)
File "/home/heronyang/.cache/bazel/_bazel_heronyang/ad9740c75005326aa53e480f56f01ef4/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 485, column 13, in _create_build_files
fail("generate_build_file.ts failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (result.stdout, result.stderr))
Error in fail: generate_build_file.ts failed: 
STDOUT:

STDERR:
could not find dependency 'sqlite3' of 'websql'
ERROR: /home/heronyang/blockchain-2pc/src/blockchain/BUILD:17:10: //src/blockchain:compile_blockchain depends on @blockchain_npm//truffle/bin:truffle in repository @blockchain_npm which failed to fetch. no such package '@blockchain_npm//truffle/bin': generate_build_file.ts failed: 
STDOUT:

STDERR:
could not find dependency 'sqlite3' of 'websql'
ERROR: Analysis of target '//src/blockchain:compile_blockchain' failed; build aborted: Analysis failed
INFO: Elapsed time: 44.562s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

**Comment by n-triple-a** [comment] 2022-05-15 00:05
Hi Heron, I'm quite not familiar git dev process. Is there a way that I can see a snapshot of your local dev workspace? Not sure if a pull request is necessary.

If I have to guess, you may need to create a dependent BUILD rule for sqlite3. You can take a look at my recent PR https://github.com/benjmarks22/blockchain-2pc/pull/6 to see if it helps. In this PR, there is a dependency chain:

//src/db:lmdb_raw_lib_example_main -> @com_drycpp_lmdbxx//:lmdb++ -> lmdb

`@com_drycpp_lmdbxx//:lmdb++` is a c++ wrapper git project that depends on the original lmdb C-implementation. Since both projects are not bazel-ed, I need to create BUILDs explicitly for both. Let me know if it helps

**Comment by heronyang** [comment] 2022-05-15 00:13
The issue happened for [heronyang-blockchain](https://github.com/benjmarks22/blockchain-2pc/tree/heronyang-blockchain) branch and it's for building the blockchain code. (You can checkout the branch and try the same bazel build command.) I'm not directly depending on sqlite but it seems our npm_install dependency depends on sqlite internally.

**Comment by benjmarks22** [comment] 2022-05-15 18:35
Should be fixed by adding sqlite3 dependency (not sure why it's needed, but it appears to fix the issue). I also added a Dockerfile so the builds should be more reproducible. See #8.

**Comment by benjmarks22** [comment] 2022-05-17 00:04
Closing as fixed.

**Closed by benjmarks22** 2022-05-17 00:04 UTC
